### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by sionisaac** [basti564/Oculess#22]
I have side loaded the apk and tried to disable companion by following the instructions to the letter.  When I run the app and choose Disable Companion and OK.  It then shows a windows titled Device Admin Apps with Companion Server and Oculess listed with switches next to them.  Companion server is running so the switch is blue.  If I click on it as described in the instructions I get a white window with companion written in the top left corner and the oculus logo (Nothing Else).  As per the instructions I rebooted the console and guess what... when I run the app again companion server is still running.  THIS DOES NOT WORK.  Please update with new instructions or inform end users that it no longer works.  Perhaps FB rushed a firmware update that killed this process but that seems unlikely as many other users are able to get this working.

Another issue.  ADB command for disabling Updates and Telemetry are not working either.  I successfully removed all accounts using the app then connected to sidequest and sent the ADB command "adb shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver" as per instructions and got the followinf error message:-

Error: Command failed: "C:\Users\Sion\AppData\Roaming\SideQuest\platform-tools\adb.exe" -s 1WMHHB61UJ1385 shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device at android.os.Parcel.createException(Parcel.java:2046) at android.os.Parcel.readException(Parcel.java:2006) at android.os.Parcel.readException(Parcel.java:1954) at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:8392) at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:203) at com.android.commands.dpm.Dpm.onRun(Dpm.java:115) at com.android.internal.os.BaseCommand.run(BaseCommand.java:65) at com.android.internal.os.BaseCommand.run(BaseCommand.java:49) at com.android.commands.dpm.Dpm.main(Dpm.java:41) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338) Caused by: android.os.RemoteException: Remote stack trace: at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:8653) at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:7822) at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:3270) at android.os.Binder.execTransactInternal(Binder.java:1021) at android.os.Binder.execTransact(Binder.java:994)

Is there any way to get this working?  Maybe update the github if this is indeed broken to save users the trouble of finding out the hard way.

**Comment by basti564** [comment]
Hello, I verified it to be still working on v35 for my device. Do you have multiple user accounts setup? That might be a problem, else try to factory reset your Quest before trying again.

**Comment by sionisaac** [comment]
If I factory reset will I lose everything including all my side loaded apps?  Once I've done the reset and say it all works.  I realise I won't be able to access the store and stock apps but can I sideload store apps as well as homebrew?  Also is this modification residual (permanent) or does it need to be done every time after shutdown and start up?

**Comment by LMFunk** [comment]
The white screens may not show anything, but the options to click them are still there. You just need to approximate where the setting would be to turn it off.

**Comment by ennis214** [comment]
I assume you are using the original quest which default came with a black theme. To see the option properly you can change the theme to white in experimental features in the quest setting.

**Comment by guzzlerman** [comment]
Hi I don't really use github but I had this issue where I was executing the command and getting the exact same error message. I dont think that this is a problem with oculess but a problem with sidequest or the link between the headset and the pc because when I unplugged my headset it still detected as connected. I reset sidequest and reallowed config on the quest and it worked. (this is a quest 1 btw)

**Comment by Nucl3arSn3k** [comment]
Hey,I'm having this same issue on a Quest 2,where the oculess app just shows a blank window when I toggle the switch I get the same white window with companion written in the top left corner and the oculus logo.

**Comment by basti564** [comment]
> Hey,I'm having this same issue on a Quest 2,where the oculess app just shows a blank window when I toggle the switch I get the same white window with companion written in the top left corner and the oculus logo.

Hello, you can fix that by changing your system theme to light mode.

**Comment by Nucl3arSn3k** [comment]
This fixed the issue,thank you.

**Comment by Chaos-Chicken** [comment]
Same issue here. I can't run the adb command after removeing all accounts.

Error: Command failed: "C:\Users\Name\AppData\Roaming\SideQuest\platform-tools\adb.exe" -s 1WMHH83FN50512 shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device at android.os.Parcel.createException(Parcel.java:2046) at android.os.Parcel.readException(Parcel.java:2006) at android.os.Parcel.readException(Parcel.java:1954) at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:8392) at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:203) at com.android.commands.dpm.Dpm.onRun(Dpm.java:115) at com.android.internal.os.BaseCommand.run(BaseCommand.java:65) at com.android.internal.os.BaseCommand.run(BaseCommand.java:49) at com.android.commands.dpm.Dpm.main(Dpm.java:41) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338) Caused by: android.os.RemoteException: Remote stack trace: at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:8653) at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:7822) at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:3270) at android.os.Binder.execTransactInternal(Binder.java:1021) at android.os.Binder.execTransact(Binder.java:994)

**Comment by Rangeclone** [comment]
SAME 

Error: Command failed: "C:\Users\range\AppData\Roaming\SideQuest\platform-tools\adb.exe" -s 1WMHHA63U11444 shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver java.lang.IllegalStateException: Not allowed to set the device owner because there are already several users on the device at android.os.Parcel.createException(Parcel.java:2046) at android.os.Parcel.readException(Parcel.java:2006) at android.os.Parcel.readException(Parcel.java:1954) at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:8392) at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:203) at com.android.commands.dpm.Dpm.onRun(Dpm.java:115) at com.android.internal.os.BaseCommand.run(BaseCommand.java:65) at com.android.internal.os.BaseCommand.run(BaseCommand.java:49) at com.android.commands.dpm.Dpm.main(Dpm.java:41) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338) Caused by: android.os.RemoteException: Remote stack trace: at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:8650) at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:7822) at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:3270) at android.os.Binder.execTransactInternal(Binder.java:1021) at android.os.Binder.execTransact(Binder.java:994)

**Comment by ProphetsWrath** [comment]
Oculus 2 Version 40 I believe I'm having an issue removing all users as I can't see any at all.  My error code when i try to run command is below and based on other threads I believe I need to remove my account but issue is how do i do this. @basti564 thanks so much for your time I appreciate you helping this new guy. 


Error: Command failed: "C:\Users\ProphetsVR\AppData\Roaming\SideQuest\platform-tools\adb.exe" -s 1WMHHA6A8T1474 shell dpm set-device-owner com.bos.oculess/.DevAdminReceiver java.lang.IllegalStateException: Not allowed to set the device owner because there are already some accounts on the device at android.os.Parcel.createException(Parcel.java:2046) at android.os.Parcel.readException(Parcel.java:2006) at android.os.Parcel.readException(Parcel.java:1954) at android.app.admin.IDevicePolicyManager$Stub$Proxy.setDeviceOwner(IDevicePolicyManager.java:8391) at com.android.commands.dpm.Dpm.runSetDeviceOwner(Dpm.java:203) at com.android.commands.dpm.Dpm.onRun(Dpm.java:115) at com.android.internal.os.BaseCommand.run(BaseCommand.java:65) at com.android.internal.os.BaseCommand.run(BaseCommand.java:49) at com.android.commands.dpm.Dpm.main(Dpm.java:41) at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method) at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:338) Caused by: android.os.RemoteException: Remote stack trace: at com.android.server.devicepolicy.DevicePolicyManagerService.enforceCanSetDeviceOwnerLocked(DevicePolicyManagerService.java:8653) at com.android.server.devicepolicy.DevicePolicyManagerService.setDeviceOwner(DevicePolicyManagerService.java:7822) at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:3269) at android.os.Binder.execTransactInternal(Binder.java:1021) at android.os.Binder.execTransact(Binder.java:994)

**Comment by threethan** [comment]
Follow the updated README. If there are still issues, reopen the issue. Currently, though, this seems impossible to replicate.
