### ISSUE TITLE
Companion Server re-enables after restart

### ISSUE THREAD

**Issue by ateich** [basti564/Oculess#48]
I'm not sure if this expected behavior, but after disabling "Companion Server" under "Device admin apps" and restarting my Oculus Quest 2, "Companion Server" is automatically re-enabled.

Telemetry and updates remain disabled on restart, and Oculess remains a "Device Owner".

Model: Quest 2
Android version: Android 10
Build number: user-28467500769800000

**Comment by basti564** [comment]
This is expected behavior. Disabling it would be of no benefit, because having it enabled alone will not bring back accounts and could have some downsides. Additionally manually disabling the companion server isn't possible anymore since a few updates since it's now a protected packages.

If you are on an older version you can try to manually disable it with the following command: 
`adb shell pm disable-user --user 0 com.oculus.companion.server
to enable it again use this command:
`adb shell pm enable com.oculus.companion.server`
